### ISSUE TITLE
Grammar and spelling errors in readme

### ISSUE THREAD

**Issue by ashinsabu** [Karanjot-singh/microsoft_teams_clone#15]
I was looking through your project's previous issues and during that, happened to find 3-4 spelling and grammatical errors in the readme file. I would love to fix it as my first contribution.

**Comment by Karanjot-singh** [comment]
Go ahead! Be sure to follow the instructions from the wiki pages

**Comment by ashinsabu** [comment]
Is it okay if I make changes using the main branch since the readme file is not present in the develop branch?

**Comment by Karanjot-singh** [comment]
> Is it okay if I make changes using the main branch since the readme file is not present in the develop branch?

For Documentation, only changes, It is alright.

**Comment by ashinsabu** [comment]
Ok 👍

**Comment by ashinsabu** [comment]
Shall I close this issue as I have made the PR for the changes?
