### ISSUE TITLE
2000 active user???

### ISSUE THREAD

**Issue by zionnite** [Karanjot-singh/microsoft_teams_clone#17]
Hello sir, 
saw this project and I think you did wonderful work on it but am kind of curious how come the project could support 2000 active users at the same time and you are using `jitsi_meet`

last time i check jitsi_meet support about 100 

> If on the free meet.jit.si, you can host a meeting with up to 100 people, but be advised that once you go above 30-35 people, you may start experiencing quality degradation.

so sir, please enlighten me on this!

thanks for all the good work, sir!

**Comment by Karanjot-singh** [comment]
Hey, Thanks for pointing it out. The "2000 active users at the same time" is for the chat functionality powered by Stream Chat SDK. I'll update the readme soon

**Comment by zionnite** [comment]
> Hey, Thanks for pointing it out. The "2000 active users at the same time" is for the chat functionality powered by Stream Chat SDK. I'll update the readme soon

Thank you, sir, 

however, I have another question

How can I make it possible for the user to host the conference themselves?

want a situation where the app users can create meeting without the acknowledgment of the Admin


Thank you so much for your time!
